default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mbta_rails_development

test:
  <<: *default
  database: mbta_rails_test

production:
  <<: *default
  database: mbta_rails_production
  username: mbta_rails
  password: <%= ENV['MBTA_RAILS_DATABASE_PASSWORD'] %>
